settings:
  files:
    outputs:
      status: false
      path: ""
      name: .r.outputs.log
    logs:
      status: false
      path: ""
      name: .r.logs.log
    errors:
      status: false
      path: ""
      name: .r.errors.log
  legacy:
    force: false
    interval: 0s
schema:
- name: cmd
  path: .
  commands:
    vet:
      status: true
    fmt:
      status: true
      args:
      - -s
      - -w
    run:
      status: true
  watcher:
    extensions:
    - go
    - yaml
    paths:
    - /
    - ../handlers/
    - ../logger/
    - ../models/
    - ../router/
    - ../utils/
    - ../config/
    - ../errors/
    - ../uploader/
    - ../middlewares/
    - ../internal/
    - ../pkg/
    - ./config.yaml
    ignored_paths:
    - .git
    - .realize
    - vendor
